[package]
name = "backend"
version = "0.2.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
actix-files = "0.6.0"
actix-session = "0.6.2"
actix-cors = "0.6.1"

async-stream = "0.3.3"
env_logger = "0.9.0"
log = "0.4.16"

meilisearch-sdk = "0.15.0"
once_cell = "1.10.0"
serde = { version = "1.0.136", features = ["derive"] }

uuid = { version = "0.8.2", features = ["serde", "v4"] }

anyhow = "1.0.56"
serde_json = "1.0.79"
