[package]
name = "backend"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
actix-session = "0.6.2"

async-stream = "0.3"
env_logger = "0.9"
log = "0.4"

meilisearch-sdk = "0.15.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }

uuid = { version = "0.8", features = ["serde", "v4"] }